# .tmux.conf
set -g default-command "${SHELL}"
set -g history-limit 500000
set -s escape-time 0
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc:Bce"
setw -g mouse on

############################################################
#
# KEY BINDINGS
#
############################################################

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# switch panes using Alt-arrow without prefix
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
set -g repeat-time 600


############################################################
#
# PLUGINS
#
############################################################

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$DOTFILE_DIR/tmux/tpm/tpm'

############################################################
#
# Theme
#
############################################################

source-file $DOTFILE_DIR/themes/current.tmux
