# .tmux.conf
set -g default-command "${SHELL}"
set -g history-limit 500000
set -s escape-time 0
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc:Bce"
setw -g mouse on

############################################################
#
# KEY BINDINGS
#
############################################################

# set C-Space as the default prefix
unbind C-b
set-option -g prefix C-Space

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# switch panes using Alt-arrow without prefix
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
set -g repeat-time 600

############################################################
#
# STATUS BAR
#
############################################################

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-left " #S "
set -g status-left-length 20
set -g status-right " %H:%M "
set -g status-right-length 20
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""

############################################################
#
# Theme
#
############################################################

source-file ~/.dotfiles/themes/current.tmux
