THEME_PROMPT_BRANCH_COLOR=242
THEME_TERMINAL_BG="#303030"

THEME_VIM_COLORSCHEME="flate2"
THEME_VIM_BACKGROUND="dark"
THEME_LSCOLORS="GxfxCxdxbxegedabagacad"

THEME_TMUX_ACTIVE_FG="colour253"
THEME_TMUX_ACTIVE_BG="colour234"
THEME_TMUX_INACTIVE_FG="colour245"
THEME_TMUX_INACTIVE_BG="colour236"
THEME_TMUX_BORDER_FG="colour242"
THEME_TMUX_ACTIVE_BORDER_FG="colour81"
