THEME_PROMPT_BRANCH_COLOR=61

THEME_TERMINAL_BG="#1c1d27"
THEME_LSCOLORS="GxfxCxdxbxegedabagacad"

THEME_TMUX_ACTIVE_FG="#c8c8d4"
THEME_TMUX_ACTIVE_BG="#1c1d27"
THEME_TMUX_INACTIVE_FG="#4a4b5e"
THEME_TMUX_INACTIVE_BG="#14151e"
THEME_TMUX_BORDER_FG="#2a2b3a"
THEME_TMUX_ACTIVE_BORDER_FG="#7c6fd4"
