THEME_PROMPT_PATH_COLOR=24        # dark teal, readable on light bg
THEME_PROMPT_BRANCH_COLOR=238     # dark grey
THEME_PROMPT_INDICATOR_COLOR=160  # red, matches cursor

THEME_TERMINAL_BG="#f2f0ec"
THEME_LSCOLORS="ExFxCxdxBxegedabagacad"

THEME_TMUX_ACTIVE_FG="#21252b"
THEME_TMUX_ACTIVE_BG="#f2f0ec"
THEME_TMUX_INACTIVE_FG="#9a9890"
THEME_TMUX_INACTIVE_BG="#e6e4e0"
THEME_TMUX_BORDER_FG="#cccac6"
THEME_TMUX_ACTIVE_BORDER_FG="#0fbd78"
