THEME_LSCOLORS="CxGxfxdxCxegedabagacad"

THEME_PROMPT_BRANCH_COLOR=220

THEME_TMUX_ACTIVE_FG="#fff0a5"
THEME_TMUX_ACTIVE_BG="#105a46"
THEME_TMUX_INACTIVE_FG="#6a7838"
THEME_TMUX_INACTIVE_BG="#0a3d2e"
THEME_TMUX_BORDER_FG="#185040"
THEME_TMUX_ACTIVE_BORDER_FG="#55ffff"
