THEME_PROMPT_BRANCH_COLOR=242

THEME_VIM_COLORSCHEME="flate2"
THEME_VIM_BACKGROUND="dark"
THEME_LSCOLORS="GxCxfxdxbxegedabagacad"

THEME_TMUX_ACTIVE_FG="#eff0eb"
THEME_TMUX_ACTIVE_BG="#282a36"
THEME_TMUX_INACTIVE_FG="#686868"
THEME_TMUX_INACTIVE_BG="#3c3e4a"
THEME_TMUX_BORDER_FG="#686880"
THEME_TMUX_ACTIVE_BORDER_FG="#57c7ff"
